### ISSUE TITLE
Multisite issue

### ISSUE THREAD

**Issue by vainucleo** [jr00ck/gravity-forms-edit-entries#3]
Hi!

Does your plugin work in multisite installation? Because when I put the shortcode(s) in a new page nothing happens, just blank...

Tnx

**Comment by jr00ck** [comment]
We actively use the plugin on a multisite install without issues. Make sure that shortcode is BEFORE the gravity forms shortcode. For example:

[gf-edit-entries]

[gravityform id="1"]

**Comment by vainucleo** [comment]
Uhm the shortcode isn't even translated...


​

2016-02-19 22:38 GMT+01:00 Jeremy Saxey <notifications@github.com>:

**Comment by jr00ck** [comment]
I'm not sure what you mean. Can you clarify if you changed the shortcode order and if anything changed?

**Comment by vainucleo** [comment]
Sorry a screenshot was supposed to be here...

I wrote shortcodes in the exact way u told me.

Ur shortcode appears as text, while GF one works correctly and shows the
original form.

Inviato dal mio Xperia™ Z5 Premium
Il 24/feb/2016 06:54 PM, "Jeremy Saxey" <notifications@github.com> ha
scritto:

**Comment by vainucleo** [comment]
![fff](https://cloud.githubusercontent.com/assets/17201475/13297215/7b274dc6-db31-11e5-9435-70224b151b6a.png)

**Comment by jr00ck** [comment]
Thanks. That usually happens when the plugin is not activated on the sub-site using the shortcode. 

The other possibility is if you go to the "Text" tab in the Editor of that page, can you see that both shortcodes have the brackets  and text showing up properly on that tab (no HTML entities or characters)?

**Comment by jr00ck** [comment]
Have you been able to find a resolution for this issue?

**Comment by vainucleo** [comment]
Honestly no, everything looks OK.

But to be completely honest I don't need it anymore at the moment, since my
client's needs changed :)

I will come back if they change again ;)

Thanks

Inviato dal mio Xperia™ Z5 Premium
Il 02/mar/2016 04:19 AM, "Jeremy Saxey" <notifications@github.com> ha
scritto:

**Comment by jr00ck** [comment]
Thanks for the response. I'm going to close this issue then, as we never got to the point of verifying if there was an actual issue. I can't replicate it and am using the plugin in the same way you are wanting to use it. 

If you have to need to address the issue in the future, please come back and let's begin the discussion again.
