### ISSUE TITLE
How can I use this plugin?

### ISSUE THREAD

**Issue by imskriaz** [jr00ck/gravity-forms-edit-entries#6]
Thanks for the great effort for this plugin.
How can I use this plugin?
Is it possible to offer the submitter on Notification and Confirmation massage with edit link.

**Comment by jr00ck** [comment]
To use the plugin, you use the standard Gravity Forms button to display the form on a page. But then to have that form also allow editing of previous entries, you have to add my plugin’s shortcode _before_ the GravityForm shortcode. For example, a page could look like this:

```
[gf-edit-entries]

[gravityform id="1" name="Time Entry" title="false" description="false"]
```

Then when that page loads, the form loads blank for a new entry. If an entry ID is appended to the URL using a query string, for example “?entry_id=245”, then the form will preload the data from the entry ID 245, and you’ll be in edit mode. You just edit anything and submit normally. 

For notifications and confirmation messages, you can add a link to the page the form is on, then use GravityForms' merge tags to append the following:

`?entry_id={entry_id}`

Keep in mind I built this quite awhile ago and while I still have it active on some sites, I’m shifting away to use the premium plugin GravityView for myself now. So I will probably not update this plugin anymore, though I’ll leave it on GitHub if other devs want to contribute. 

Hope that helps. Good luck!

**Comment by imskriaz** [comment]
Thank you
